import type { Engagement } from './types'
import { nanoid } from 'nanoid'

export const sampleEngagement: Engagement = {
  id: nanoid(),
  accountName: 'Acme Corp',
  name: 'Acme - Onboarding',
  status: 'IN_PROGRESS',
  health: 'GREEN', // This will be automatically calculated based on status
  assignedRep: 'Sam Rep',
  startDate: '2025-07-10',
  closeDate: '2025-09-15',
  salesType: 'Direct Sell',
  speed: 'Medium',
  crm: 'Salesforce',
  soldBy: 'John Sales',
  seatCount: 50,
  hoursAlloted: 120,
  primaryContactName: 'Jane Smith',
  primaryContactEmail: 'jane.smith@acmecorp.com',
  linkedinLink: 'https://www.linkedin.com/in/janesmith',
  avazaLink: 'https://app.avaza.com/projects/12345',
  projectFolderLink: 'https://drive.google.com/drive/folders/abc123',
  clientWebsiteLink: 'https://www.acmecorp.com',
  addOnsPurchased: ['Meet', 'Deal', 'Forecasting'],
  milestones: [
    {
      id: nanoid(),
      name: 'Kick-Off',
      stage: 'COMPLETED',
      owner: 'Sam Rep',
      dueDate: '2025-07-12',
      isStandard: true,
    },
    {
      id: nanoid(),
      name: 'Workflow Design',
      stage: 'WORKSHOP',
      owner: 'Sam Rep',
      dueDate: '2025-07-22',
      isStandard: true,
    },
    {
      id: nanoid(),
      name: 'Content Strategy',
      stage: 'INITIAL_CALL',
      owner: 'Taylor Rep',
      dueDate: '2025-07-25',
      isStandard: true,
    },
    {
      id: nanoid(),
      name: 'CRM Integration',
      stage: 'INITIAL_CALL',
      owner: 'Riley Rep',
      dueDate: '2025-08-10',
      isStandard: true,
    },
    {
      id: nanoid(),
      name: 'Data Migration',
      stage: 'NOT_STARTED',
      owner: 'Riley Rep',
      dueDate: '2025-08-20',
      isStandard: true,
    },
    {
      id: nanoid(),
      name: 'Change Readiness',
      stage: 'NOT_STARTED',
      owner: 'Casey Rep',
      dueDate: '2025-08-08',
      isStandard: true,
    },
    {
      id: nanoid(),
      name: 'User Training',
      stage: 'NOT_STARTED',
      owner: 'Sam Rep',
      dueDate: '2025-08-25',
      isStandard: true,
    },
    {
      id: nanoid(),
      name: 'User Office Hours',
      stage: 'NOT_STARTED',
      owner: 'Sam Rep',
      dueDate: '2025-08-30',
      isStandard: true,
    },
    {
      id: nanoid(),
      name: 'Manager Training',
      stage: 'NOT_STARTED',
      owner: 'Taylor Rep',
      dueDate: '2025-08-28',
      isStandard: true,
    },
    {
      id: nanoid(),
      name: 'Admin Training',
      stage: 'NOT_STARTED',
      owner: 'Taylor Rep',
      dueDate: '2025-08-29',
      isStandard: true,
    },
  ],
}
